version: '3'

volumes:
  db_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    image: mrterr1ble/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/backend_media
  frontend:
    image: mrterr1ble/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: mrterr1ble/foodgram_gateway
    env_file: .env
    ports:
      - 8080:80
    depends_on:
      - backend
    volumes:
      - static:/static
      - media:/media
