# Generated by Django 3.2.16 on 2025-02-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_shortlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlink',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipes.shortlink'),
        ),
    ]
