# Generated by Django 3.2.16 on 2025-02-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20250210_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_link',
        ),
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
