# Generated by Django 3.2.3 on 2025-01-31 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250130_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введен некорекнтый логин.', regex='^[\\w.@+-]+$')], verbose_name='Имя пользователя'),
        ),
    ]
